# version: '3'

networks:
  zen_network:

services:
  nginx:
    image: public.ecr.aws/nginx/nginx:stable-perl
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    networks:
      zen_network:
        aliases:
          - nginx
  website:
    container_name: 'brentgarden'
    image: websites/brentgarden
    volumes:
      - ./ssl/:/.ssl
    restart: always
    networks:
      zen_network:
        aliases:
          - brentgarden
